### PR TITLE
PhpUnit 8 support

### PR DESCRIPTION
**Pull request by Naktibalda**
I solved signature change problem with `setUp`, `tearDown` and `setUpBeforeClass`,
but I have no idea how to solve a problem of final class declarations.

`PHP Fatal error:  Class Codeception\PHPUnit\Runner may not inherit from final class (PHPUnit\TextUI\TestRunner)`
Other final class that we used to extend are `\PHPUnit\Runner\Filter\NameFilterIterator` and `\PHPUnit\Util\Log\JUnit`.

### CODE REVIEW

**Review by DavertMik — APPROVED** [review]
Looks good. Overriding final classes is the only option.
At least there was not too much thing to override.

**Comment by b1rdex** [comment]
Some tests are failed becuase https://github.com/sebastianbergmann/php-code-coverage/pull/667 is not released yet.

**Comment by b1rdex** [comment]
sebastianbergmann/php-code-coverage 7.0.2 tagged with fix fix of type errors.

**Comment by Naktibalda** [comment]
@b1rdex now the tests are failing because of https://github.com/Codeception/Codeception/issues/5397

**Comment by Naktibalda** [comment]
And one more thing to fix:
`[PHPUnit\Framework\Warning] Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.`
PHPUnit Warning counts as failure, so it is necessary to replace all `assertContains` with string haystack with something else.

**Pull request merged**
