### PR TITLE
Fix error due to release of phpunit/php-code-coverage v9 (#5949)

### PR DESCRIPTION
**Pull request by simonhammes**
Quick and dirty fix for https://github.com/Codeception/Codeception/issues/5949

More info: https://github.com/Codeception/Codeception/issues/5949#issuecomment-671639237

### CODE REVIEW

**Comment by Naktibalda** [comment]
It will do for now, but a better fix is necessary.

**Comment by Naktibalda** [comment]
Released as 9.0.3

**Comment by BrunoSpy** [comment]
If I remove `"phpunit/php-code-coverage": "^8.0.0",` fomr  my composer.json, this is what I have (not the behaviour expected) :

```bash
php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 3 installs, 6 updates, 1 removal
  - Removing phpunit/php-token-stream (4.0.4)
  - Updating sebastian/global-state (4.0.0 => 5.0.0): Loading from cache
  - Updating phar-io/version (2.0.1 => 3.0.2): Loading from cache
  - Updating phar-io/manifest (1.0.3 => 2.0.1): Loading from cache
  - Installing nikic/php-parser (v4.9.0): Downloading (100%)         
  - Installing sebastian/lines-of-code (1.0.0): Loading from cache
  - Installing sebastian/complexity (2.0.0): Loading from cache
  - Updating phpunit/php-code-coverage (8.0.2 => 9.1.4): Downloading (100%)         
  - Updating phpunit/phpunit (9.2.6 => 9.3.7): Downloading (100%)         
  - Downgrading codeception/phpunit-wrapper (9.0.3 => 9.0.2): Loading from cache
```

My composer.json dev section : 
```php
"require-dev": {
        "phpunit/phpunit": "^9.0",
        "codeception/codeception": "^4.0",
        "sensiolabs/security-checker": "^6.0.0",
        "api-skeletons/doctrine-data-fixture": "^6.0",
        "laminas-api-tools/api-tools-admin": "^1.8",
        "laminas/laminas-log": "^2.10",
        "laminas/laminas-router": "^3.3",
        "laminas/laminas-component-installer": "^2.1",
        "codeception/module-webdriver": "^1.0.0",
        "codeception/module-asserts": "^1.0.0",
        "codeception/module-zf2": "^1.0.0",
        "codeception/module-doctrine2": "^1.0.0",
        "laminas/laminas-developer-tools": "^2.0"
```

**Comment by Naktibalda** [comment]
Yes, that's what usually happens when you try to reduce the range of supported versions.
Composer prefers newer version of phpunit with older version of phpunit-wrapper over older phpunit with newer phpunit-wrapper.

**Pull request merged**
